### ISSUE TITLE
Implement XML validator 

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#10]
1. Load an XML schema
2. Pass an xml document and show whether the XML is valid or not.

**Comment by lohithgn** [comment]
@dodyg what folder should this sample be placed ?

**Comment by dodyg** [comment]
a new folder xml. It's a lost art.

**Comment by lohithgn** [comment]
projects > xml ?

**Comment by dodyg** [comment]
yup. Then put xml-validator (or something similar) for the project inside the projects > xml folder.

**Comment by lohithgn** [comment]
Ok. I have it now as projects > xml > XmlValidation

**Comment by lohithgn** [comment]
PR created - https://github.com/dodyg/practical-aspnetcore/pull/290
