### ISSUE TITLE
rss/atom river of news server

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#11]
1. Pass a list of rss/atom feeds via config
2. Render them nicely

**Comment by lohithgn** [comment]
working on this...

**Comment by lohithgn** [comment]
Where should this example be placed ? inside projects > syndications folder ?

**Comment by dodyg** [comment]
Yup

**Comment by lohithgn** [comment]
PR created - https://github.com/dodyg/practical-aspnetcore/pull/288
