### ISSUE TITLE
Consolidate logging examples

### ISSUE THREAD

**Issue by neman** [dodyg/practical-aspnetcore#127]
I do not see why there is the existence of both https://github.com/dodyg/practical-aspnetcore/tree/master/projects/logging and https://github.com/dodyg/practical-aspnetcore/tree/master/projects/hello-world-with-logging

They are practically the same. I think that hello world with logging should be removed.

Also, https://github.com/dodyg/practical-aspnetcore/tree/master/projects/logging-with-filter is practically the same as https://github.com/dodyg/practical-aspnetcore/tree/master/projects/hello-world-with-logging-filtered.

My suggestion is that hello world examples should be removed (but before that just make sure to merge them with other examples since its code is a bit more concise)

Any new logging examples should be prefixed with `logging` within their name.

For example, I have an idea to show logging as early as possible, and I would call that project/folder `logging-early-as-possible`.

Maybe you should think of putting examples in their dedicated folders since now there are a more than 140 examples. So logging would take its logging folder and so on, but that is for some different issue.

**Comment by dodyg** [comment]
Those examples were created because 1.1 and 2.0 had different ways of doing logging. They ended up being the same once migrated to 2.1. I will remove them next week unless you want to do a PR.

Good idea on the folder grouping. Some samples such as middleware can be grouped.

**Comment by neman** [comment]
You can assign me to this task and I will do the PR.
