### ISSUE TITLE
Sample for user, role and groups management

### ISSUE THREAD

**Issue by weedkiller** [dodyg/practical-aspnetcore#159]
Hi can you add some smaple for users and roles please

Users in roles
Roles with users
mapping actions to roles

**Comment by dodyg** [comment]
I will get to it. Yeah, identity is a whole huge section in ASP.NET Core and they sometimes can be very confusing.

**Comment by AdrienTorris** [comment]
@dodyg I worked a lot with Identity on ASP.NET Core, tell me if you want I push some samples about this (I don't know if you prefer to do this on your own or if you want a lots of contributions to build the most complete repository possible about ASP.NET Core).

**Comment by dodyg** [comment]
That is great. @AdrienTorris  go ahead. I want lots of contributions. The faster we can build the micro samples, the better it is for everybody. 

I think we can reach 300 - 400 samples and still won't cover the surface API and functionality of ASP.NET Core and associated techs.

**Comment by AdrienTorris** [comment]
It's coming ... ;) (it will be done maybe tomorrow, this week-end at the latest)
![identity-sample-is-coming](https://user-images.githubusercontent.com/1014357/49245662-51e02480-f413-11e8-8aee-43f21479f8da.png)

**Comment by AdrienTorris** [comment]
@dodyg How do you want to organize the projects folder? 

* projects/identity/basic-authentication
* projects/security/authentication-with-identity
* projects/security/basic-authentication-with-identity
* projects/security/basic-authentication-with-identity-and-sqlite (I'm using SQLite to store the users because it can be stored as a dll by the web app so the sample can be a self-contained project with no external dependencies)

Let me know the organization you want for this.

**Comment by dodyg** [comment]
Let's just put everything under the folder /security, then we can put identity, authentication, authorization, etc under that folder. It's such a critical topic and it deserves its own section.

**Comment by weedkiller** [comment]
Yes please put it in one project, this would be a great starter project template

**Comment by Kralizek** [comment]
@dodyg do you want only strict asp.net core codebase samples or do you accept related libraries?

I was thinking about building on top of @AdrienTorris work a sample using AWS Cognito identity provider

**Comment by dodyg** [comment]
@Kralizek related libraries are fine. I have created nswag, orchardcore, etc samples. Just please add an extensive description on the readme of the project.

**Comment by dodyg** [comment]
> Yes please put it in one project, this would be a great starter project template

I am in two minds about starter project template. Security is such a fragile thing: it's super easy to mess up security if you don't know understand whats' going on. I rather we go for increasing people's understanding and mastery than convenience. If one of the sample becomes a starting point, then great but it shouldn't be the goal.

**Comment by AdrienTorris** [comment]
If you want a great and complete starter project (with external signins, password recovery, ...) you have just to create a new ASP.NET Core web application with authentication, all will be created for you (@dodyg using a Razor Class Library if you choose .NET Core 2.2 by the way ;) )

**Comment by dodyg** [comment]
Oh neat. I gotta try that.

**Comment by dodyg** [comment]
One neat sample would be showing people a straightforward away to implement granular ACL.

**Comment by AdrienTorris** [comment]
a granular ACL?

**Comment by dodyg** [comment]
Access Control List. Sometimes there are systems that require a pretty granular access control e.g

Manager A:

- Allow to edit this page
- But not add
- View is allows
- But not delete

Manager B:

- View only

So each user role has a list of checkboxes that show what kind of access it has.

**Comment by AdrienTorris** [comment]
Ok, let's do that!

**Comment by AdrienTorris** [comment]
Another sample that would be great is to custom Identity to integrate an Organization layer (allow to have several organizations in the same Identity service). We often have to do this by our own. I could do it too, but roles and policies first ;)

**Comment by AdrienTorris** [comment]
@dodyg Because I don't want you to sleep at night: https://techcrunch.com/2018/12/10/google-security-bug-gave-developers-access-to-non-public-data-from-52-5m-users/

**Comment by dodyg** [comment]
@AdrienTorris Lol. This security thing is a nightmare.

**Comment by weedkiller** [comment]
Also being able to separate users under the same role, has access to limited/ different groups 

For eg East coast managers vs West coast managers ... Each budgets data should be only available to each of their areas, and what's the best way to handle that.

Would that be claims or groups

**Comment by jannikbuschke** [comment]
@weedkiller I think thats neither claims nor groups. In microsoft terms this would be called Resource Based Access Control (RBAC), where authorization is not only determined by facts about the user (claims/group membership) but also the resource/object being accessed.

**Comment by weedkiller** [comment]
Helllo @jannikbuschke thanks for the response, you are correct I am looking for a sample to managed the user specifc resource, I thought it was a claim.

I looked for a sample, but RBAC is actually `Role `Based Access Control, [MS website](https://devblogs.microsoft.com/premier-developer/role-based-access-control-in-asp-net-mvc/)


Any chance we can still get a sample to show how manages those groups of managers inside a manager role

**Comment by jannikbuschke** [comment]
Here is a bit of dotnet documentation about Resource Based Authorization: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-3.1

To filter data in EF Core query filters can be utilized: https://docs.microsoft.com/en-us/ef/core/querying/filters (this could be handy to implement Reads with RBAC)

**Comment by dodyg** [comment]
@weedkiller  this is a good library to use for RBAC https://github.com/casbin/Casbin.NET. I haven't had a chance to implement a sample for this but it's on my todo list.
