### ISSUE TITLE
[Question] Plans for .NET Core 3?

### ISSUE THREAD

**Issue by AdrienTorris** [dodyg/practical-aspnetcore#165]
Hi @dodyg 

What are your plans for .NET Core 3? Do you want to update the existing samples from .NET 2.2 to .NET 3 or you prefer re-implement them? If you prefer re-implement them, how do you want to organize the samples? A folder"3-0" under the 'projects' folder? 

I start for a few days to play with .NET Core 3, I can start to post some samples but I prefer have your guidelines first.

**Comment by AdrienTorris** [comment]
For information, I did some basic samples on .NET Core 3 and there is no difference with .NET Core 2.2 for now, except for the WPF stuff of course. But they are very basic, some differences may appears with more advanced samples.

**Comment by neman** [comment]
The best would be to have separate branch while 3.0 is in preview. I think there is no bred to reimplement, just update is enough.
Let’s see @dodyg idea about this.

**Comment by dodyg** [comment]
For 3.0 only samples:

- Create 3-0 folder
- Put a global.json there
- Put all your ASP .NET Core 3.0 specific samples in that folder

2.1 is an LTS release. Existing samples that's in 2.1 should stay there as long as possible. If your sample doesn't require 2.2 or higher, keep them in 2.1. 

We will have to revisit this topic in 6 months when ASP.NET Core 3.0 solidifies. We might need to branch at that point.

Regarding re-implementation, let's take it on a case by case basis and only when it is absolutely necessary for clarity. For example, we will need a hello world example for ASP.NET Core 3.0 if the the way the hosting is configured differently than 2.1.

**Comment by AdrienTorris** [comment]
Ok. Si if there is no difference between .NET Core 3.0 (preview) and .NET Core 2.2, I do not post any sample. It's clear, thanks.

**Comment by dodyg** [comment]
https://github.com/aspnet/Announcements/issues/331

**Comment by dodyg** [comment]
https://github.com/aspnet/Announcements/issues/325

**Comment by dodyg** [comment]
https://www.strathweb.com/2019/01/collectible-assemblies-in-net-core-3-0/

**Comment by dodyg** [comment]
https://www.telerik.com/blogs/razor-components-for-a-javascript-free-frontend-in-2019

**Comment by dodyg** [comment]
A new section for 3.0 is here https://github.com/dodyg/practical-aspnetcore/tree/master/projects/3-0
