### ISSUE TITLE
Show example of trailing header in aspnetcore 3

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#194]

**Comment by dodyg** [comment]
https://github.com/aspnet/AspNetCore/issues/10519

**Comment by dodyg** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer

**Comment by Tratcher** [comment]
Here's an example of response trailers:
https://github.com/aspnet/AspNetCore/blob/806fef3a278c01f55ffd98a539ea6bd8ceeabf48/src/Servers/Kestrel/samples/Http2SampleApp/TimingMiddleware.cs

**Comment by dodyg** [comment]
https://github.com/dodyg/practical-aspnetcore/tree/master/projects/3-0/trailing-headers
