### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#196]
https://github.com/richlander/testapps/blob/master/versioninfo/Program.cs

**Comment by Kralizek** [comment]
could you add a sample of the output as a comment at the end of the file? Like Microsoft does in their documention

**Comment by dodyg** [comment]
Can you please provide a link on how it looks like when Microsoft does it? I am not familiar with it.

**Comment by Kralizek** [comment]
This is the first place that came to my mind

https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings

**Comment by dodyg** [comment]
https://github.com/dodyg/practical-aspnetcore/tree/master/projects/3-0/version
