### ISSUE TITLE
Add samples for .NET 5

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#228]
https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/

**Comment by dodyg** [comment]
This will mostly related to https://github.com/dodyg/practical-aspnetcore/tree/3.1-LTS/projects/json

**Comment by ehsansajjad-synergy** [comment]
> This will mostly related to https://github.com/dodyg/practical-aspnetcore/tree/3.1-LTS/projects/json

@dodyg  did you mean : https://github.com/dodyg/practical-aspnetcore/tree/3.1-LTS/projects/5-0

**Comment by dodyg** [comment]
Yes but most of the practical implication so far is with enhancement to ```System.Text.Json```

**Comment by dodyg** [comment]
I migrated 9 JSON samples to .NET 5 https://github.com/dodyg/practical-aspnetcore/tree/3.1-LTS/projects/5-0

**Comment by lohithgn** [comment]
what else is needed on this issue ?

**Comment by dodyg** [comment]
Circular reference in System.Text.Json

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-preserve-references?pivots=dotnet-5-0

**Comment by dodyg** [comment]
Virtualization in Blazor and a couple of more new things in .NET 5

https://www.codemag.com/Article/2010102/Blazor-Updates-in-.NET-5
