### ISSUE TITLE
Blazor radio button support

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#258]
https://gist.github.com/SQL-MisterMagoo/bc5713fb26bf84bf810d48d1f45c361a#gistcomment-3593887

**Comment by lohithgn** [comment]
Are you looking for a sample which showcase just the radiobutton selection handling ( like the gist in the link you have provided ) ?

**Comment by dodyg** [comment]
Yes. 

The sample needs to demonstrate how to use Radio buttons on at least two choices.

**Comment by lohithgn** [comment]
PR created: https://github.com/dodyg/practical-aspnetcore/pull/277
