### ISSUE TITLE
Write a simple HTTP Proxy

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#27]

**Comment by dodyg** [comment]
https://github.com/aspnet/Proxy

**Comment by lohithgn** [comment]
```https://github.com/aspnet/Proxy``` is archived and has been moved to aspnetlabs. That means - its still an experiment and is not ready for production.

Currently the recommended one is YARP - https://github.com/microsoft/reverse-proxy

**Comment by lohithgn** [comment]
https://microsoft.github.io/reverse-proxy/articles/getting_started.html

**Comment by dodyg** [comment]
Yeah we should be writing a sample using YARP instead.
