### ISSUE TITLE
Create samples for MapAction

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#271]

**Comment by dodyg** [comment]
https://github.com/dodyg/practical-aspnetcore/tree/net5.0/projects/net6/map-action

**Comment by Kralizek** [comment]
This could be interesting to create a endpoint-oriented application 🤔

**Comment by dodyg** [comment]
Yeah there are so many possibilities

**Comment by dodyg** [comment]
Samples are here https://github.com/dodyg/practical-aspnetcore/tree/net5.0/projects/net6
