### ISSUE TITLE
Add RenderFragment method sample for Blazor

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#274]

**Comment by lohithgn** [comment]
@dodyg do you mind if i work on this ? I can create a simple example of RenderFragment based on the official doc - https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-5.0

Thoughts ?

**Comment by lohithgn** [comment]
@dodyg i have created a pull request - [PR275](https://github.com/dodyg/practical-aspnetcore/pull/275)

Do have a look at it. Merge it if its according to what you had in mind.

Thanks.

**Comment by dodyg** [comment]
It's really nice. Next time please add a `README.md` on the project folder and put a credit. I added it for now https://github.com/dodyg/practical-aspnetcore/tree/net5.0/projects/blazor/RenderFragment

**Comment by lohithgn** [comment]
@dodyg ahh i see. Thanks. May be you can close this issue for now then.
