### ISSUE TITLE
Create samples for the new Minimal Hosting APIs

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#276]

**Comment by dodyg** [comment]
This is the first sample https://github.com/dodyg/practical-aspnetcore/tree/net5.0/projects/net6/hello-world

**Comment by dodyg** [comment]
The next step is to add sample for `WebApplication.CreateBuilder()`

**Comment by lohithgn** [comment]
@dodyg you may want to check this issue https://github.com/dotnet/aspnetcore/issues/32432 ... Damian feels the WebApplication.CreateBuilder() is inefficient at the moment ... they are investigating this ...
