### ISSUE TITLE
Add samples for System.Text.Json writable DOM

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#285]
https://github.com/dotnet/designs/blob/main/accepted/2020/serializer/WriteableDomAndDynamic.md

**Comment by lohithgn** [comment]
Whats your idea on this ? I mean - if we were to showcase this i.e. System.Text.Json writable dom - in ASP.NET Core - what sample idea works ?

**Comment by dodyg** [comment]
One of the primary usage for this writable DOM is the ability to modify an existing JSON document without deserializing them into objects and then serializing it again. 
For example https://gist.github.com/keeguon/2310008. How would you add "wakanda" into this list of countries?

**Comment by dodyg** [comment]
We can make the following samples

* [ ] Find a simple node and update its value
* [ ] Find a nested object node and update one of its value
* [ ] Find a nested object node and replace it 
* [ ] Append an item at the end an array.
* [ ] Insert an item an n position in an array
* [ ] Replace an item in an array.
* [ ] Find an object within an array and replace one of its value
* [ ] Replace a property of number and change it to a string value

There are probably more granular examples we can create.

**Comment by dodyg** [comment]
This adds the sample of accessing primitives from JSON string

https://github.com/dodyg/practical-aspnetcore/commit/1da2bfccfc8b67402bec5e83cf6238ecf523dc43

**Comment by dodyg** [comment]
This adds a sample about accessing object and using `JsonObject`.

https://github.com/dodyg/practical-aspnetcore/commit/7a766b588ddc1ce0b914d553d471f55b18e0b69f

**Comment by dodyg** [comment]
This adds a sample on how to find a node based on one of its value

https://github.com/dodyg/practical-aspnetcore/commit/9704265cdb816ff6fab4f65a38ce791474392f13

**Comment by dodyg** [comment]
This is a slightly more complex node LINQ search on a string property and an array

https://github.com/dodyg/practical-aspnetcore/commit/4f3e6e5e1b490f5d7cb601d6dfcc877d788f193b

**Comment by dodyg** [comment]
This LINQ search try to find a node that doesn't have a particular property

https://github.com/dodyg/practical-aspnetcore/commit/eec8a4cf7f97dd661e2a4062b49866ad2bb42663

**Comment by dodyg** [comment]
This shows how to create a document using `JsonObject` https://github.com/dodyg/practical-aspnetcore/commit/195178c483d39a861ebbf5b31c9231c5aba0e346

**Comment by dodyg** [comment]
This shows how to create a document with `JsonArray` https://github.com/dodyg/practical-aspnetcore/commit/7215c5093a1b8d91a96744d664ea35620fbff51c

**Comment by dodyg** [comment]
This shows how to update properties of a JSON document https://github.com/dodyg/practical-aspnetcore/commit/9b1060206a9d99bc2028f7b00d81e7bd8198887d

**Comment by dodyg** [comment]
Delete elements in a document https://github.com/dodyg/practical-aspnetcore/commit/809fc40e2eeac35c411e8224ca6b6c6be5d01020

**Comment by dodyg** [comment]
Add elements into a JSON array https://github.com/dodyg/practical-aspnetcore/commit/968a1f1814595300813f229a57e28501dd0815ef
