### ISSUE TITLE
MultiChannel Server Sent Event (aka SSE)

### ISSUE THREAD

**Issue by tebeco** [dodyg/practical-aspnetcore#29]
Will provide a dummy implementation

**Comment by dodyg** [comment]
Oh awesome. I am looking forward to it. This is the first time I heard of SSE.

**Comment by tebeco** [comment]
Streaming event :
* Easier than web socket (no need for hardware proxy etc..)
* Native in browser
* support reconnect / replay
* support multi event type 
* BUT only one way (server to client)

http://hpbn.co
There's a really well explained chapter
