### ISSUE TITLE
Write simple samples for YARP

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#293]

**Comment by lohithgn** [comment]
i will take this. 

@dodyg can you add this to the project , assign it to my name and out it to inprogress.

On a side note: you can make me a contributor. then i can assign it myself and set its status. Let me know

**Comment by lohithgn** [comment]
YARP docs: https://microsoft.github.io/reverse-proxy/index.html

**Comment by lohithgn** [comment]
@dodyg YARP team has a bunch of samples on github. Here is the link: https://github.com/microsoft/reverse-proxy/tree/main/samples

Do we need everything copied here to practical-aspnetcore ?

**Comment by lohithgn** [comment]
What should be the path to the sample: projects/reverse-proxy/basic-yarp-sample

**Comment by dodyg** [comment]
>What should be the path to the sample: projects/reverse-proxy/basic-yarp-sample

projects/yarp is better and straightforward

**Comment by dodyg** [comment]
> Do we need everything copied here to practical-aspnetcore ?

https://github.com/microsoft/reverse-proxy/tree/main/samples/ReverseProxy.Minimal.Sample

This is nice but it needs to go simpler. We need to pair it with a running hello world that you can just run and test the proxy with.

**Comment by dodyg** [comment]
> On a side note: you can make me a contributor. then i can assign it myself and set its status. Let me know

done

**Comment by lohithgn** [comment]
> > What should be the path to the sample: projects/reverse-proxy/basic-yarp-sample
> 
> projects/yarp is better and straightforward

Well.... Reverse proxy is the concept. YARP is one of the software/package that let's you do it...

**Comment by dodyg** [comment]
yeah but realistically we are not going to add samples for other packages/tech that is not YARP such as NGINX, HAProxy...

**Comment by lohithgn** [comment]
> > Do we need everything copied here to practical-aspnetcore ?
> 
> https://github.com/microsoft/reverse-proxy/tree/main/samples/ReverseProxy.Minimal.Sample
> 
> This is nice but it needs to go simpler. We need to pair it with a running hello world that you can just run and test the proxy with.

How about: 
- a blazor wasm front end runs at https://localhost:5001
- a asp.net core web api backend runs at https://localhost:5002
- YARP runs at https://localhost:5003 with following routes set up:
   -  "/" -> proxies to -> https://localhost:5001
   - "/api" -> proxies to -> https://localhost:5002

**Comment by lohithgn** [comment]
the yarp minimal sample demo is possible only with net6.0 preview 4. If we want to do the minimal sample for yarp - this will need to be in projects/net6/yarp. else if we go the old Startup way this can be in projects/yarp ... 

@dodyg what do you think ?

**Comment by dodyg** [comment]
net6/yarp for now. Then when net6 is launched we move it to /projects/

**Comment by lohithgn** [comment]
PR created - https://github.com/dodyg/practical-aspnetcore/pull/296
