### ISSUE TITLE
Implement a pokemon data server using minimal API

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#318]
https://github.com/robert-z/simple-pokemon-json-api

**Comment by lohithgn** [comment]
Will work on it. Seems perfect for .NET 6 Minimal API

**Comment by lohithgn** [comment]
@dodyg where should this be created ? here `practical-aspnetcore\projects\net6` ??

If yes - i am thinking of the name as `minimal-api-pokedex` as a folder in front of `practical-aspnetcore\projects\net6` ?

**Comment by dodyg** [comment]
Looks good.

**Comment by lohithgn** [comment]
@dodyg 

Please review this [commit](https://github.com/dodyg/practical-aspnetcore/commit/13bd569ca92ca81e729be3c9175817f645d89eff)
and 
this pr #321 

Those two updates take care of this issue

**Comment by dodyg** [comment]
This is awesome 🔥
