### ISSUE TITLE
Sanity check

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#319]
@lohithgn can you please run this sample in RC2 and see if it works?

https://github.com/dodyg/practical-aspnetcore/tree/net5.0/projects/net6/web-application-builder-4

I filed a confirmed bug on this exact code on RC1 and the case was confirmed closed (https://github.com/dotnet/aspnetcore/issues/36999). However I still can't make it work on RC2.

**Comment by lohithgn** [comment]
@dodyg sure. i will check it out.

**Comment by dodyg** [comment]
I will close this. The fix is not in RC2. It will be available on `WebApplicationOptions`.
