### ISSUE TITLE
Really dig into middleware

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#51]
There are still problem with clarity in the consequences of middleware 

https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/middleware/sample

**Comment by dodyg** [comment]
https://andrewlock.net/understanding-your-middleware-pipeline-with-the-middleware-analysis-package/#addingacustomnameforanonymousmiddleware

**Comment by dodyg** [comment]
https://stackoverflow.com/questions/45330103/access-tempdata-within-custom-middleware

**Comment by Tratcher** [comment]
Temp data? Goss. 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2

**Comment by dodyg** [comment]
I just stumbled on the topic. Not sure why one would use Temp data for passing data from the Middleware when HttpContext.Items is available, but it's doable apparently..
