### ISSUE TITLE
Data protection

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#54]
https://github.com/aspnet/DataProtection

**Comment by lohithgn** [comment]
New docs page: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-5.0

**Comment by lohithgn** [comment]
The old repo contains examples here: https://github.com/aspnet/DataProtection/tree/master/samples

We can just recreate them here ...

where should this samples go ?

**Comment by lohithgn** [comment]
this can be at this path: projects > security > data-protection > src > sample-1...etc

**Comment by neman** [comment]
Looks good to me. Stick with the existing docs convention (although this repo folder is just security, not security-and-identity, which is I guess understandable enough)

![image](https://user-images.githubusercontent.com/350314/120637659-78152e00-c46f-11eb-9301-1345e3b53b01.png)

**Comment by lohithgn** [comment]
@neman  that was my thoughts too ... the official docs have them under security & identity. But dataprotection is more of just security and not identity. And in this repo - we just have security folder. so will create them under security

**Comment by lohithgn** [comment]
@dodyg can you add this issue to Project here -https://github.com/dodyg/practical-aspnetcore/projects/1 -  and assign it to me. set it to in progress.
Thanks.

**Comment by lohithgn** [comment]
see if you can add all issues to the project. that way we know which ones are in which phase.

that will surely help contributors.

**Comment by dodyg** [comment]
Done. Yeah let's do some rudimentary project management here.

**Comment by lohithgn** [comment]
Finished 3 demos so far:
- default settings
- with blob storage
- with key vault & blob storage

You can check the progress here: https://github.com/lohithgn/practical-aspnetcore/tree/lohithgn/issue-54

**Comment by lohithgn** [comment]
@dodyg this is done now. PR #295 fixes this. Following demos are available:
- Default Settings
- Key Persistence using Azure Storage Blob
- Key Persistence using Azure Storage Blob & Key Encryption using Azure Key Vault
- Key Persistence using relation database and EF Core data context
- Key Persistence using Redis
- Key Persistence using custom XML encryptor

Once merged issue can be closed (on project board can be moved to done)
