### ISSUE TITLE
Suggestion: Top-level folder for everything

### ISSUE THREAD

**Issue by nickwalkmsft** [dodyg/practical-aspnetcore#64]
Saw this on Reddit; love the idea.

I have a small, GitHub-specific suggestion: It doesn't seem there's a technical reason to have all the directories at the top level, so put them into a subdir so they don't put the top of the readme "below the fold" on the GitHub project page.

**Comment by dodyg** [comment]
Will do. Thanks.

**Comment by dodyg** [comment]
This is done. All the sample codes are under /projects.
