### ISSUE TITLE
Explore session

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#66]

**Comment by dodyg** [comment]
Session With Memory Cache
Session With Redis Cache

**Comment by dodyg** [comment]
Redis Cache implemented. As does Memory Cache.

**Comment by Tratcher** [comment]
https://github.com/dodyg/practical-aspnetcore/blob/1e93a310b623e9ef5a82dd5e1c6d3a92b3ee1539/projects/features-session/src/Program.cs#L24-L47
https://github.com/dodyg/practical-aspnetcore/blob/1e93a310b623e9ef5a82dd5e1c6d3a92b3ee1539/projects/aspnet-core-2/features-session-redis/src/Program.cs#L66-L95
It's a little strange to use session for communication within a request. Items works better for that. Session is for cross-request state.

Also, avoid BinaryFormatter at all costs. Json (Newtonsoft.Json) a common way people serialize complex session data.

**Comment by dodyg** [comment]
Thanks for the feedback.

The point of the code is simply to show the mechanic of using a Redis session using BinaryFormatter.  I will add another sample on how to use Json.  I will make a note on the example.

BinaryFormatter is handy for caching complex objects that cannot be handled by  to Redis.
