### ISSUE TITLE
Razor pages example

### ISSUE THREAD

**Issue by lukiasz** [dodyg/practical-aspnetcore#71]
Hello,

I'm familiarizing with .NET Core 2.0 in which there is nice feature called [Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/). Would you mind if I contribute to your project and add few examples of it?

**Comment by dodyg** [comment]
Go ahead. Please add them under a mvc/razor-pages folders.

**Comment by lukiasz** [comment]
I created pull request: https://github.com/dodyg/practical-aspnetcore/pull/73

**Comment by dodyg** [comment]
Both projects are now on readme.
