### ISSUE TITLE
IHostedService

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#90]
https://blogs.msdn.microsoft.com/webdev/2017/08/25/asp-net-core-2-0-features-1/

**Comment by dodyg** [comment]
https://www.stevejgordon.co.uk/asp-net-core-2-ihostedservice

**Comment by Tratcher** [comment]
https://github.com/aspnet/Docs/issues/3352

**Comment by dodyg** [comment]
Simple sample

https://github.com/dodyg/practical-aspnetcore/tree/master/projects/aspnet-core-2/ihosted-service
